version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: pnpm run start:dev
    container_name: app
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '${APP_HTTP_PORT:-}:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - app_net
      - redis_net

  redis:
    image: redis
    container_name: redis
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - '${REDIS_PORT:-}:6379'
    volumes:
      - redis_vol:/data
    networks:
      - redis_net

volumes:
  redis_vol:
    name: redis_vol

networks:
  app_net:
    name: app_net
  redis_net:
    name: redis_net
    driver: bridge
