version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: pnpm run start:dev
    container_name: app
    env_file:
      - ./.env
    ports:
      - '3000:30000'
    volumes:
      - .:/usr/src/app
    networks:
      - app_net

networks:
  app_net:
    name: app_net
    driver: bridge
